version: "3"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: Admin123
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
